version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
     # Mode: Menggunakan KRaft
      CLUSTER_ID: "EmptNWtoR4GGWx-BH6nGLQ" # ID unik (bisa digenerate sekali)
      KAFKA_BROKER_ID: 1
      
      # Peran Broker: Menjadi Controller dan Broker (Combined Mode)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      
      # Konfigurasi Listener
      KAFKA_LISTENERS: "PLAINTEXT_EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka:9093,PLAINTEXT_INTERNAL://kafka:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT_INTERNAL'
      # Koneksi antar Broker/Controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      
      # Lokasi Penyimpanan Log Metadata
      KAFKA_LOG_DIRS: "/tmp/kraft-storage"
    volumes:
      - ./data-kafka:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_CLUSTERS_0_ZOOKEEPER: ""  # kosongkan untuk KRaft mode
    depends_on:
      - kafka

volumes:
  kafka-data:
    driver: local